---
title: "CodeBook"
author: "Littal"
date: "December 26, 2015"
output: html_document
---

#Researcher Dictionary: Getting & Cleaning Data - Project

#Human activities recorded while wearing a smartphone

#Version 1.0

#December 26, 2015 



###INTRODUCTION

The project data represent data collected from the accelerometers from the Samsung Galaxy S smartphone. 
The data was originally obtained from: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 
The following description was found at that site:

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years.

Each person performed six activities (WALKING, WALKING UPSTAIRS, WALKING DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. 

Using its embedded accelerometer and gyroscope, the experiment captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. 

The experiments have been video-recorded to label the data manually. 

The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). 

The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. 

The gravitational force is assumed to have low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. 

From each window, a vector of features was obtained by calculating variables from the time and frequency domain.

For each record in the dataset it is provided: 

	- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration. 
	
	- Triaxial Angular velocity from the gyroscope. 
	
	- A 561-feature vector with time and frequency domain variables. 
	
	- Its activity label. 
	
	- An identifier of the subject who carried out the experiment.
	

###DATASET DESCRIPTION

To obtain the project dataset, a zip file was downloaded from the following URL: 
https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip 

Using R script called run_analysis.R, the following processes revealed this dataset, called "SecondTidyData": 

*Merges the training and the test sets to create one data set.

*Extracts only the measurements on the mean and standard deviation for each measurement. 

*Uses descriptive activity names to name the activities in the data set.

*Appropriately labels the data set with descriptive variable names. 

*Creates a second, independent tidy data set with the average of each variable for each activity and each subject.



For specific details about the work flow of creating this dataset, called "SecondTidyData", please read the ReadMe file in the project repo.

###LIST OF VARIABLES

SubjectCode

ActivityCode 

TimeBodyAccelometer.MEAN...X

TimeBodyAccelometer.MEAN...Y

TimeBodyAccelometer.MEAN...Z

TimeGravityAccelometer.MEAN...X

TimeGravityAccelometer.MEAN...Y

TimeGravityAccelometer.MEAN...Z

TimeBodyAccelometerJerk.MEAN...X

TimeBodyAccelometerJerk.MEAN...Y

TimeBodyAccelometerJerk.MEAN...Z

TimeBodyGyroscope.MEAN...X

TimeBodyGyroscope.MEAN...Y

TimeBodyGyroscope.MEAN...Z

TimeBodyGyroscopeJerk.MEAN...X

TimeBodyGyroscopeJerk.MEAN...Y

TimeBodyGyroscopeJerk.MEAN...Z

TimeBodyAccelometerMagnitude.MEAN..

TimeGravityAccelometerMagnitude.MEAN..

TimeBodyAccelometerJerkMagnitude.MEAN..

TimeBodyGyroscopeMagnitude.MEAN..

TimeBodyGyroscopeJerkMagnitude.MEAN..

FrequencyBodyAccelometer.MEAN...X

FrequencyBodyAccelometer.MEAN...Y

FrequencyBodyAccelometer.MEAN...Z

FrequencyBodyAccelometerJerk.MEAN...X

FrequencyBodyAccelometerJerk.MEAN...Y

FrequencyBodyAccelometerJerk.MEAN...Z

FrequencyBodyGyroscope.MEAN...X

FrequencyBodyGyroscope.MEAN...Y

FrequencyBodyGyroscope.MEAN...Z

FrequencyBodyAccelometerMagnitude.MEAN..

FrequencyBodyBodyAccelometerJerkMagnitude.MEAN..

FrequencyBodyBodyGyroscopeMagnitude.MEAN..

FrequencyBodyBodyGyroscopeJerkMagnitude.MEAN..

TimeBodyAccelometer.STD...X

TimeBodyAccelometer.STD...Y

TimeBodyAccelometer.STD...Z

TimeGravityAccelometer.STD...X

TimeGravityAccelometer.STD...Y

TimeGravityAccelometer.STD...Z

TimeBodyAccelometerJerk.STD...X

TimeBodyAccelometerJerk.STD...Y

TimeBodyAccelometerJerk.STD...Z

TimeBodyGyroscope.STD...X

TimeBodyGyroscope.STD...Y

TimeBodyGyroscope.STD...Z

TimeBodyGyroscopeJerk.STD...X

TimeBodyGyroscopeJerk.STD...Y

TimeBodyGyroscopeJerk.STD...Z

TimeBodyAccelometerMagnitude.STD..

TimeGravityAccelometerMagnitude.STD..

TimeBodyAccelometerJerkMagnitude.STD..

TimeBodyGyroscopeMagnitude.STD..

TimeBodyGyroscopeJerkMagnitude.STD..

FrequencyBodyAccelometer.STD...X

FrequencyBodyAccelometer.STD...Y

FrequencyBodyAccelometer.STD...Z

FrequencyBodyAccelometerJerk.STD...X

FrequencyBodyAccelometerJerk.STD...Y

FrequencyBodyAccelometerJerk.STD...Z

FrequencyBodyGyroscope.STD...X

FrequencyBodyGyroscope.STD...Y

FrequencyBodyGyroscope.STD...Z          

FrequencyBodyAccelometerMagnitude.STD..   

FrequencyBodyBodyAccelometerJerkMagnitude.STD..

FrequencyBodyBodyGyroscopeMagnitude.STD..     

FrequencyBodyBodyGyroscopeJerkMagnitude.STD..  



